# YOLOv11 Training Configuration
# This file contains all training parameters for the drone detection model

# Model Configuration
model_variant: "yolov11n"  # Options: yolov11n, yolov11s, yolov11m, yolov11l, yolov11x
pretrained: true
num_classes: 3
class_names:
  - "vehicle"
  - "person" 
  - "building"

# Training Parameters
epochs: 100
batch_size: 16
learning_rate: 0.01
momentum: 0.937
weight_decay: 0.0005
warmup_epochs: 3
warmup_momentum: 0.8
warmup_bias_lr: 0.1

# Image Parameters
image_size: 640
augment: true
mixup: 0.0
copy_paste: 0.0

# Optimization Parameters
optimizer: "SGD"  # Options: SGD, Adam, AdamW
lr_scheduler: "cosine"  # Options: linear, cosine
cos_lr: false

# Loss Parameters
box_loss_gain: 7.5
cls_loss_gain: 0.5
dfl_loss_gain: 1.5

# Validation Parameters
val_split: 0.2
save_period: 10
patience: 50

# Hardware Parameters
device: "auto"  # Options: auto, cpu, cuda, cuda:0, etc.
workers: 8

# Paths
data_path: ""  # Will be set via command line or environment
project_path: "runs/detect"
name: "yolov11_drone_detection"

# MLFlow Parameters
experiment_name: "yolov11-drone-detection"
run_name: null  # Will be auto-generated if null

# Advanced Training Parameters
# Uncomment and modify as needed

# Data Augmentation (advanced)
# hsv_h: 0.015
# hsv_s: 0.7
# hsv_v: 0.4
# degrees: 0.0
# translate: 0.1
# scale: 0.5
# shear: 0.0
# perspective: 0.0
# flipud: 0.0
# fliplr: 0.5
# mosaic: 1.0

# Loss Function Weights
# focal_loss_gamma: 0.0
# label_smoothing: 0.0

# Model Architecture
# depth_multiple: 1.0
# width_multiple: 1.0

# Training Strategy
# close_mosaic: 10  # Epochs to close mosaic augmentation
# amp: true  # Automatic Mixed Precision
# fraction: 1.0  # Dataset fraction to use
# profile: false  # Profile training speed
# freeze: null  # Layers to freeze during training

# Hyperparameter Evolution
# evolve: false
# evolve_population: 50
# evolve_generations: 300
# evolve_mutation: 0.8
# evolve_sigma: 0.2

# Logging and Visualization
# plots: true
# save_json: false
# save_hybrid: false
# conf: null
# iou: 0.7
# max_det: 300
# half: false
# dnn: false
# verbose: true